# -*- coding: utf-8 -*-
"""Customer Clustering using Hierarchical clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oVpZKUSiPC_Udrq6NGT__4kOHTMV3Ix4
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd ..
from google.colab import drive
drive.mount('/content/gdrive')

# rename path
!ln -s /content/gdrive/My\ Drive/ /mydrive
#!ls /mydrive

import pandas as pd
import matplotlib.pyplot as plt

path = '/mydrive/Data_Science_Projects/Customer_Clustering_using_Hierarchical_clustering/data/'

df = pd.read_csv(path + 'segmentation_data.csv')
df.head(10)

df.describe()

"""Dendogram Visualization"""

import scipy.cluster.hierarchy as clust

plt.figure(1, figsize=(16, 8))
dendrogram = clust.dendrogram(clust.linkage(df, method='ward'))

plt.title("Dendrogram graph")
plt.xlabel("Customer")
plt.ylabel("Distance")
plt.show()

"""Fitting Hierarchical clustering with n=5"""

from sklearn.cluster import AgglomerativeClustering


# affinity: default='euclidean' - 'euclidean', 'l1', 'l2', 'manhattan', 'cosine', or 'precomputed
# linkage{‘ward’, ‘complete’, ‘average’, ‘single’}, default=’ward’
model = AgglomerativeClustering(n_clusters=5, affinity="euclidean", linkage="ward")
y_means = model.fit_predict(df)
y_means

"""## Vizualizing the numbers of the *clusters*



"""

X = df.iloc[:,[3,5]].values
plt.scatter(X[y_means == 0,0], X[y_means == 0,1], s=50, c='orange', label='Cluster 1')
plt.scatter(X[y_means == 1,0], X[y_means == 1,1], s=50, c='purple', label='Cluster 2')
plt.scatter(X[y_means == 2,0], X[y_means == 2,1], s=50, c='blue', label='Cluster 3')
plt.scatter(X[y_means == 3,0], X[y_means == 3,1], s=50, c='red', label='Cluster 4')
plt.scatter(X[y_means == 4,0], X[y_means == 4,1], s=50, c='green', label='Cluster 5')
plt.title("Income by Age (Hierarchical clustering)")
plt.xlabel('Age')
plt.ylabel('Income')
plt.legend()
plt.show()

